version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: strip-ansi
    versions:
    - ">= 7.a, < 8"
  - dependency-name: mock-fs
    versions:
    - 4.14.0
